services:
    rmcgirr83.separateusersandbots.listener:
        class: rmcgirr83\separateusersandbots\event\listener
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@template'
            - '@user'
            - '@?rmcgirr83.hidebots.listener'
        tags:
            - { name: event.listener }
